### ISSUE TITLE
Falsey values can't be cached

### ISSUE THREAD

**Issue by chriscdn** [murtazazaidi/lrucache#4]
The `get` function returns null if the cached value is falsey.  E.g., zero.

Here's the relevant part in the `get` function:

	this.get = function (key) {
	    var data = _this.data[key];
	    if (!data) {
	      return null;
	    }
	    
Zero is, of course, a valid cached value.

**Comment by murtazazaidi** [comment]
@chriscdn thanks for raising this. This should be fixed now in v1.2.0
https://github.com/murtazazaidi/lrucache/pull/5
